sudo: required
services:
  - docker

before_install:
  - docker build -t miguelangeltorresfp/docker-kubernetes-react-tutorial -f Dockerfile.dev .

script:
  - docker run miguelangeltorresfp/docker-kubernetes-react-tutorial npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-kubernetes-react-tutorial"
  env: "DockerKubernetesReactTutorial-env"
  bucket_name: "elasticbeanstalk-eu-west-1-633762040595"
  bucket_path: "docker-kubernetes-react-tutorial"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
